"use client";

import {PointerEvent,useEffect,useRef,useState} from "react";
import "./floating-tools.css";

const pitches=["C","C♯","D","E♭","E","F","F♯","G","A♭","A","B♭","B"];
const semitones:Record<string,number>={C:0,"C♯":1,D:2,"E♭":3,E:4,F:5,"F♯":6,G:7,"A♭":8,A:9,"B♭":10,B:11};

export default function FloatingPracticeTools(){const [open,setOpen]=useState(false),[tab,setTab]=useState<"tuner"|"metronome"|"drone">("tuner"),[position,setPosition]=useState({x:0,y:0}),[bpm,setBpm]=useState(76),[metro,setMetro]=useState(false),[note,setNote]=useState("A"),[octave,setOctave]=useState(4),[drones,setDrones]=useState<string[]>([]),[listening,setListening]=useState(false),[heard,setHeard]=useState("A4"),[cents,setCents]=useState(0);const drag=useRef<{x:number;y:number;px:number;py:number}|null>(null),audio=useRef<AudioContext|null>(null),timer=useRef<number|null>(null),oscillators=useRef(new Map<string,OscillatorNode>()),stream=useRef<MediaStream|null>(null),frame=useRef<number|null>(null);
  useEffect(()=>()=>{if(timer.current)clearInterval(timer.current);oscillators.current.forEach(o=>o.stop());stream.current?.getTracks().forEach(t=>t.stop());if(frame.current)cancelAnimationFrame(frame.current);audio.current?.close()},[]);const context=()=>audio.current??(audio.current=new AudioContext());
  function pointerDown(e:PointerEvent<HTMLDivElement>){drag.current={x:e.clientX,y:e.clientY,px:position.x,py:position.y};e.currentTarget.setPointerCapture(e.pointerId)}function pointerMove(e:PointerEvent<HTMLDivElement>){if(!drag.current)return;setPosition({x:drag.current.px+e.clientX-drag.current.x,y:drag.current.py+e.clientY-drag.current.y})}function pointerUp(){drag.current=null}
  function tick(){const c=context(),o=c.createOscillator(),g=c.createGain();o.frequency.value=900;g.gain.setValueAtTime(.07,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.05);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.05)}function toggleMetro(){if(metro){if(timer.current)clearInterval(timer.current);timer.current=null;setMetro(false)}else{tick();timer.current=window.setInterval(tick,60000/bpm);setMetro(true)}}useEffect(()=>{if(!metro)return;if(timer.current)clearInterval(timer.current);timer.current=window.setInterval(tick,60000/bpm);return()=>{if(timer.current)clearInterval(timer.current)}},[bpm,metro]);
  function toggleDrone(){const key=`${note}${octave}`,old=oscillators.current.get(key);if(old){old.stop();oscillators.current.delete(key)}else{const c=context(),o=c.createOscillator(),g=c.createGain(),midi=(octave+1)*12+semitones[note];o.type="triangle";o.frequency.value=440*2**((midi-69)/12);g.gain.value=.025;o.connect(g).connect(c.destination);o.start();oscillators.current.set(key,o)}setDrones([...oscillators.current.keys()])}
  async function toggleTuner(){if(listening){stream.current?.getTracks().forEach(t=>t.stop());if(frame.current)cancelAnimationFrame(frame.current);setListening(false);return}const media=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=media;const c=context(),source=c.createMediaStreamSource(media),analyser=c.createAnalyser(),data=new Float32Array(2048);analyser.fftSize=2048;source.connect(analyser);const loop=()=>{analyser.getFloatTimeDomainData(data);let crossings=0;for(let i=1;i<data.length;i++)if(data[i-1]<0&&data[i]>=0)crossings++;const hz=crossings*c.sampleRate/data.length;if(hz>150&&hz<2200){const midi=Math.round(69+12*Math.log2(hz/440)),target=440*2**((midi-69)/12);setHeard(`${pitches[(midi+120)%12]}${Math.floor(midi/12)-1}`);setCents(Math.max(-50,Math.min(50,Math.round(1200*Math.log2(hz/target)))))}frame.current=requestAnimationFrame(loop)};loop();setListening(true)}
  return <><button className="practice-fab" onClick={()=>setOpen(!open)}><span>⌁</span>{open?"Close tools":"Practice tools"}</button>{open&&<section className="floating-tools" style={{transform:`translate(${position.x}px,${position.y}px)`}}><div className="floating-handle" onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp}><span>Practice console</span><i>⠿ drag</i></div><nav>{(["tuner","metronome","drone"] as const).map(value=><button key={value} className={tab===value?"active":""} onClick={()=>setTab(value)}>{value}</button>)}</nav><div className="floating-body">{tab==="tuner"&&<div className="float-tuner"><small>CONCERT PITCH</small><b>{heard}</b><div><i style={{transform:`translateX(${cents*1.4}px)`}}/></div><span>{cents>0?`${cents}¢ sharp`:cents<0?`${Math.abs(cents)}¢ flat`:"in tune"}</span><button onClick={toggleTuner}>{listening?"Stop listening":"Use microphone"}</button></div>}{tab==="metronome"&&<div className="float-metro"><small>TEMPO</small><b>{bpm}</b><span>BPM</span><input type="range" min="40" max="180" value={bpm} onChange={e=>setBpm(+e.target.value)}/><button className={metro?"stop":""} onClick={toggleMetro}>{metro?"■ Stop":"▶ Start"}</button></div>}{tab==="drone"&&<div className="float-drone"><div><select value={note} onChange={e=>setNote(e.target.value)}>{pitches.map(p=><option key={p}>{p}</option>)}</select><select value={octave} onChange={e=>setOctave(+e.target.value)}>{[3,4,5,6].map(o=><option key={o}>{o}</option>)}</select></div><button onClick={toggleDrone}>{drones.includes(`${note}${octave}`)?"Stop":"Start"} {note}{octave}</button><p>{drones.length?`Playing ${drones.join(" + ")}`:"No drone playing"}</p></div>}</div></section>}</>}
