"use client";

import {useEffect,useState} from "react";
import {createPortal} from "react-dom";
import {readSessions,type PracticeSession} from "./practice-data";
import "./practice-activity-hero.css";

function dateKey(date:Date){return `${date.getFullYear()}-${date.getMonth()+1}-${date.getDate()}`}
function streaks(active:Set<string>){let current=0,cursor=new Date();while(active.has(dateKey(cursor))){current++;cursor=new Date(cursor.getTime()-86400000)}let longest=0,run=0;for(let i=364;i>=0;i--){const day=new Date(Date.now()-i*86400000);if(active.has(dateKey(day))){run++;longest=Math.max(longest,run)}else run=0}return {current,longest}}

export default function PracticeActivityHero(){const [mount,setMount]=useState<Element|null>(null),[sessions,setSessions]=useState<PracticeSession[]>([]);useEffect(()=>{if(location.pathname!=="/flute-studio")return;setMount(document.querySelector(".studio-hero"));const update=()=>setSessions(readSessions());update();window.addEventListener("cookie:practice-updated",update);return()=>window.removeEventListener("cookie:practice-updated",update)},[]);if(!mount)return null;const today=new Date(),todayStart=new Date(today.getFullYear(),today.getMonth(),today.getDate()).getTime(),weekStart=todayStart-6*86400000,minutes=(list:PracticeSession[])=>Math.round(list.reduce((n,s)=>n+s.durationSeconds,0)/60),todayMinutes=minutes(sessions.filter(s=>new Date(s.startedAt).getTime()>=todayStart)),weekMinutes=minutes(sessions.filter(s=>new Date(s.startedAt).getTime()>=weekStart)),byDay=new Map<string,number>();sessions.forEach(s=>{const key=dateKey(new Date(s.startedAt));byDay.set(key,(byDay.get(key)??0)+s.durationSeconds/60)});const active=new Set([...byDay].filter(([,value])=>value>0).map(([key])=>key)),streak=streaks(active),cells=Array.from({length:84},(_,i)=>{const date=new Date(todayStart-(83-i)*86400000),value=Math.round(byDay.get(dateKey(date))??0);return {date,value}}),level=(value:number)=>value===0?0:value<10?1:value<25?2:value<45?3:4;return createPortal(<div className="practice-activity-hero"><div className="activity-heading"><span>YOUR PRACTICE ACTIVITY</span><h2>Consistency, not perfection.</h2><p>Every focused session counts.</p></div><div className="activity-stats"><article><b>{todayMinutes}</b><span>min today</span></article><article><b>{weekMinutes}</b><span>min this week</span></article><article><b>{streak.current}</b><span>day streak</span></article><article><b>{streak.longest}</b><span>longest streak</span></article></div><div className="activity-calendar"><div className="heatmap" aria-label="Twelve weeks of practice activity">{cells.map(cell=><i key={cell.date.toISOString()} className={`level-${level(cell.value)}`} title={`${cell.date.toLocaleDateString()}: ${cell.value} minutes`}/>)}</div><footer><span>12 weeks</span><div>Less <i className="level-0"/><i className="level-1"/><i className="level-2"/><i className="level-3"/><i className="level-4"/> More</div></footer></div></div>,mount)}
