"use client";

import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";
import {readSessions,type PracticeSession} from "./practice-data";
import "./practice-activity-hero.css";

const dayMs=86400000;
function dateKey(date:Date){return `${date.getFullYear()}-${date.getMonth()+1}-${date.getDate()}`}
function streaks(active:Set<string>){let current=0,cursor=new Date();while(active.has(dateKey(cursor))){current++;cursor=new Date(cursor.getTime()-dayMs)}let longest=0,run=0;for(let i=364;i>=0;i--){const day=new Date(Date.now()-i*dayMs);if(active.has(dateKey(day))){run++;longest=Math.max(longest,run)}else run=0}return {current,longest}}

export default function PracticeActivityHero(){
  const [mount,setMount]=useState<Element|null>(null),[sessions,setSessions]=useState<PracticeSession[]>([]),[monthOffset,setMonthOffset]=useState(0);
  useEffect(()=>{if(location.pathname!=="/flute-studio")return;setMount(document.querySelector(".studio-hero"));const update=()=>setSessions(readSessions());update();window.addEventListener("cookie:practice-updated",update);return()=>window.removeEventListener("cookie:practice-updated",update)},[]);
  const data=useMemo(()=>{const today=new Date(),todayStart=new Date(today.getFullYear(),today.getMonth(),today.getDate()).getTime(),weekStart=todayStart-6*dayMs,minutes=(list:PracticeSession[])=>Math.round(list.reduce((n,s)=>n+s.durationSeconds,0)/60),byDay=new Map<string,number>();sessions.forEach(s=>{const key=dateKey(new Date(s.startedAt));byDay.set(key,(byDay.get(key)??0)+s.durationSeconds/60)});const active=new Set([...byDay].filter(([,value])=>value>0).map(([key])=>key));return {todayMinutes:minutes(sessions.filter(s=>new Date(s.startedAt).getTime()>=todayStart)),weekMinutes:minutes(sessions.filter(s=>new Date(s.startedAt).getTime()>=weekStart)),byDay,streak:streaks(active)}},[sessions]);
  if(!mount)return null;
  const shown=new Date(new Date().getFullYear(),new Date().getMonth()+monthOffset,1),daysInMonth=new Date(shown.getFullYear(),shown.getMonth()+1,0).getDate(),leading=shown.getDay(),cells=Array.from({length:leading+daysInMonth},(_,i)=>i<leading?null:new Date(shown.getFullYear(),shown.getMonth(),i-leading+1)),level=(value:number)=>value===0?0:value<10?1:value<25?2:value<45?3:4;
  return createPortal(<div className="practice-activity-hero"><div className="activity-summary"><span>YOUR PRACTICE ACTIVITY</span><h2>{data.streak.current?`${data.streak.current} days in a row.`:"Start with one focused session."}</h2><div className="activity-stats"><article><b>{data.todayMinutes}</b><span>min today</span></article><article><b>{data.weekMinutes}</b><span>min this week</span></article><article><b>{data.streak.current}</b><span>current streak</span></article><article><b>{data.streak.longest}</b><span>best streak</span></article></div></div><section className="month-calendar" aria-label="Monthly practice calendar"><header><button onClick={()=>setMonthOffset(v=>v-1)} aria-label="Previous month">‹</button><strong>{shown.toLocaleDateString(undefined,{month:"long",year:"numeric"})}</strong><button onClick={()=>setMonthOffset(v=>Math.min(0,v+1))} disabled={monthOffset===0} aria-label="Next month">›</button></header><div className="weekday-row">{["S","M","T","W","T","F","S"].map((d,i)=><span key={`${d}${i}`}>{d}</span>)}</div><div className="month-grid">{cells.map((date,i)=>date?<div key={dateKey(date)} className={`day-cell level-${level(Math.round(data.byDay.get(dateKey(date))??0))}`} title={`${date.toLocaleDateString()}: ${Math.round(data.byDay.get(dateKey(date))??0)} minutes`}><span>{date.getDate()}</span><i/></div>:<div className="day-cell empty" key={`empty-${i}`}/>)}</div><footer><span>Minutes practiced</span><div>None <i className="level-0"/><i className="level-1"/><i className="level-2"/><i className="level-3"/><i className="level-4"/> More</div></footer></section></div>,mount)
}
