"use client";

import {useEffect,useState} from "react";
import {createPortal} from "react-dom";
import {activeKey,formatDuration,readSessions,sessionsKey,type ActivePractice,type PracticeSession} from "./practice-data";
import "./practice-session.css";

function currentItem(){if(location.pathname.includes("mystery-of-love"))return {itemId:"mystery-of-love",itemType:"repertoire" as const,title:"Mystery of Love"};if(location.pathname.includes("exercises/scales"))return {itemId:"scale-studio",itemType:"exercise" as const,title:"Scale Studio"};return null}

export default function PracticeSessionTimer(){const [mount,setMount]=useState<Element|null>(null),[item,setItem]=useState<ReturnType<typeof currentItem>>(null),[active,setActive]=useState<ActivePractice|null>(null),[seconds,setSeconds]=useState(0),[finishing,setFinishing]=useState(false),[reflection,setReflection]=useState("");useEffect(()=>{const selected=currentItem();setItem(selected);if(!selected)return;setMount(document.querySelector(".topbar>div:last-child")??document.querySelector(".scale-main>header"));const stored=localStorage.getItem(activeKey);if(stored){const parsed=JSON.parse(stored) as ActivePractice;if(parsed.itemId===selected.itemId)setActive(parsed)}},[]);useEffect(()=>{if(!active)return;const update=()=>setSeconds(Math.max(0,Math.floor((Date.now()-new Date(active.startedAt).getTime())/1000)));update();const id=window.setInterval(update,1000);return()=>clearInterval(id)},[active]);if(!mount||!item)return null;function start(){if(!item)return;const next:ActivePractice={...item,startedAt:new Date().toISOString()};localStorage.setItem(activeKey,JSON.stringify(next));setActive(next);setSeconds(0)}function cancel(){localStorage.removeItem(activeKey);setActive(null);setFinishing(false);setSeconds(0)}function finish(){if(!active)return;const endedAt=new Date(),duration=Math.max(1,Math.floor((endedAt.getTime()-new Date(active.startedAt).getTime())/1000)),session:PracticeSession={id:crypto.randomUUID(),...active,endedAt:endedAt.toISOString(),durationSeconds:duration,reflection:reflection.trim()},sessions=[session,...readSessions()];localStorage.setItem(sessionsKey,JSON.stringify(sessions));localStorage.removeItem(activeKey);window.dispatchEvent(new Event("cookie:practice-updated"));setActive(null);setFinishing(false);setReflection("");setSeconds(0)}return createPortal(<div className="session-control">{!active?<button className="start-practice" onClick={start}><span>◷</span>Start practicing</button>:<><button className="running-practice" onClick={()=>setFinishing(!finishing)}><i/> {formatDuration(seconds)} <b>Finish</b></button>{finishing&&<div className="finish-session-pop"><small>FINISH PRACTICE</small><strong>{formatDuration(seconds)} on {item.title}</strong><textarea value={reflection} onChange={e=>setReflection(e.target.value)} placeholder="What did you work on? (optional)"/><div><button onClick={cancel}>Discard</button><button onClick={finish}>Save session</button></div></div>}</>}</div>,mount)}
