"use client";

import { PointerEvent, useEffect, useRef, useState } from "react";
import type { OpenSheetMusicDisplay as OSMDType } from "opensheetmusicdisplay";

const pitchClasses = ["C", "C♯", "D", "E♭", "E", "F", "F♯", "G", "A♭", "A", "B♭", "B"];
const semitones: Record<string, number> = { C:0,"C♯":1,D:2,"E♭":3,E:4,F:5,"F♯":6,G:7,"A♭":8,A:9,"B♭":10,B:11 };
const scorePhrase = ["B4","G4","B4","A4","G4","G4","E4","D4",null,"E4","F♯4","G4","D5","B4","A4"];
const mysteryScoreSequence = Array.from({length:4},()=>scorePhrase).flat();
const eventPhrase = [{p:"B4",d:6},{p:"G4",d:2},{p:"B4",d:2},{p:"A4",d:1},{p:"G4",d:1},{p:"G4",d:2},{p:"E4",d:2},{p:"D4",d:12},{p:null,d:4},{p:"E4",d:4},{p:"F♯4",d:4},{p:"G4",d:4},{p:"D5",d:4},{p:"B4",d:8},{p:"A4",d:8}];
const mysteryScoreEvents = Array.from({length:4},()=>eventPhrase).flat();
const mysteryMeasureStarts = Array.from({length:4},(_,group)=>[0,7,9,13].map(index=>index+group*15)).flat();
export type ScoreViewerConfig={title:string;asset:string;id:string;backHref:string;pitches:(string|null)[];events:{p:string|null;d:number}[];measureStarts:number[];subtitle?:string};
const mysteryConfig:ScoreViewerConfig={title:"Mystery of Love",asset:"/mystery-of-love.mxl",id:"mystery-of-love",backHref:"/flute-studio/music",pitches:mysteryScoreSequence,events:mysteryScoreEvents,measureStarts:mysteryMeasureStarts};
const fingeringKeys:Record<string,string[]>={C4:["L1","REb"],D4:["T","L1","L2","L3","R1","R2","R3"],E4:["T","L1","L2","L3","R1","R2","REb"],"F♯4":["T","L1","L2","L3","R2","REb"],F4:["T","L1","L2","L3","R1","REb"],G4:["T","L1","L2","L3","REb"],A4:["T","L1","L2","REb"],B4:["T","L1","REb"],C5:["L1","REb"],D5:["T","L2","L3","R1","R2","R3"],E5:["T","L1","L2","L3","R1","R2","REb"],F5:["T","L1","L2","L3","R1","REb"],"F♯5":["T","L1","L2","L3","R2","REb"],G5:["T","L1","L2","L3","REb"],A5:["T","L1","L2","REb"],B5:["T","L1","REb"],C6:["L1","REb"],D6:["T","L2","L3","R1","R2","R3"],E6:["T","L1","L2","L3","R1","R2","REb"],"F♯6":["T","L1","L2","L3","R2","REb"],G6:["T","L1","L2","L3","REb"]};
type RhythmMode = "off"|"counts"|"bars";
function fingeringOn(pitch:string,key:string){return (fingeringKeys[pitch]??[]).includes(key)}
function measureForEvent(index:number,measureStarts:number[]){let result=1;measureStarts.forEach((start,i)=>{if(start<=index)result=i+1});return result}
function overlay(root:HTMLDivElement,className:string,text:string,x:number,y:number){const item=document.createElement("span");item.className=`practice-overlay ${className}`;item.textContent=text;item.style.left=`${x}px`;item.style.top=`${y}px`;root.appendChild(item)}
function placePracticeOverlays(root:HTMLDivElement,scoreEvents:{p:string|null;d:number}[],measureStarts:number[]){root.querySelectorAll(".practice-overlay").forEach(n=>n.remove());const rootBox=root.getBoundingClientRect(),all=[...root.querySelectorAll<SVGGElement>(".vf-stavenote[data-event]")];all.forEach(note=>{const event=scoreEvents[Number(note.dataset.event)],box=note.getBoundingClientRect(),x=box.left-rootBox.left+box.width/2,y=box.bottom-rootBox.top+7;if(event?.p){overlay(root,"note-name-marker",event.p.replace(/\d/,""),x,y);if(event.p.includes("♯"))overlay(root,"accidental-marker","♯",x,box.top-rootBox.top-18)}const measure=Number(note.dataset.measure),start=measureStarts[measure-1]??0,index=Number(note.dataset.event);let onset=0;for(let i=start;i<index;i++)onset+=scoreEvents[i]?.d??0;const sixteenth=Math.round(onset);overlay(root,"count-marker",`${Math.floor(sixteenth/4)+1}${["","e","+","a"][sixteenth%4]}`,x,y+15)});for(let measure=1;measure<=measureStarts.length;measure++){const group=all.filter(n=>Number(n.dataset.measure)===measure);if(!group.length)continue;const start=measureStarts[measure-1],end=measureStarts[measure]??scoreEvents.length;let onset=0;const anchors=group.map((node,i)=>{const eventIndex=start+i,box=node.getBoundingClientRect(),anchor={t:onset,x:box.left-rootBox.left+box.width/2};onset+=scoreEvents[eventIndex]?.d||0;return anchor});const ancestor=group[0].closest<SVGGElement>(".vf-measure"),measureBox=ancestor?.getBoundingClientRect(),right=measureBox?measureBox.right-rootBox.left:anchors.at(-1)!.x+34;anchors.push({t:16,x:right});const top=(measureBox?.top??Math.min(...group.map(n=>n.getBoundingClientRect().top)))-rootBox.top-7;for(let beat=0;beat<4;beat++){const target=beat*4,left=[...anchors].reverse().find(a=>a.t<=target)??anchors[0],next=anchors.find(a=>a.t>=target)??anchors.at(-1)!,ratio=next.t===left.t?0:(target-left.t)/(next.t-left.t);overlay(root,"beat-stick","",left.x+(next.x-left.x)*ratio,top)}}}
function addTheoryTargets(root:HTMLDivElement){const targets:[[string,string],...[string,string][]]=[[".vf-clef","Treble clef: the curl circles the G line. Flute music is normally written in this clef."],[".vf-keysignature","Key signature: one sharp means every F is played as F-sharp unless an accidental changes it."],[".vf-timesignature","Time signature: the top number gives beats per measure; the bottom number identifies the beat value."],[".vf-stavetie","Tie: hold the connected notes as one continuous sound. Do not tongue the second note."]];targets.forEach(([selector,text])=>root.querySelectorAll<SVGElement>(selector).forEach(node=>{node.dataset.theory=text;node.classList.add("theory-target")}))}

function prepareScore(xml: string,title:string) {
  const document = new DOMParser().parseFromString(xml, "application/xml");
  document.querySelector("work-title")?.replaceChildren(title);
  document.querySelectorAll('creator[type="composer"]').forEach(node => node.remove());
  return new XMLSerializer().serializeToString(document);
}

export function ScoreViewer({config=mysteryConfig}:{config?:ScoreViewerConfig}) {
  const {title,asset,id,backHref,pitches:scoreSequence,events:scoreEvents,measureStarts}=config;
  const scoreRef = useRef<HTMLDivElement>(null); const canvasRef = useRef<HTMLCanvasElement>(null); const osmdRef = useRef<OSMDType | null>(null);
  const audioRef = useRef<AudioContext | null>(null); const dronesRef = useRef(new Map<string,OscillatorNode>()); const playbackTimers=useRef<number[]>([]); const playbackNodes=useRef<OscillatorNode[]>([]); const metroRef = useRef<number | null>(null); const metroBeat=useRef(0); const metroTaps=useRef<number[]>([]); const drawing = useRef(false); const inkHistory=useRef<string[]>([]); const inkIndex=useRef(-1);
  const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [bpm,setBpm]=useState(76); const [startMeasure,setStartMeasure]=useState(1); const [playing,setPlaying]=useState(false); const [metro,setMetro]=useState(false); const [accent,setAccent]=useState(true); const [activeDrones,setActiveDrones]=useState<string[]>([]); const [dronePitch,setDronePitch]=useState("G"); const [droneOctave,setDroneOctave]=useState(4); const [picker,setPicker]=useState(false); const [annotating,setAnnotating]=useState(false); const [inkColor,setInkColor]=useState("#e45d46"); const [eraser,setEraser]=useState(false); const [historyTick,setHistoryTick]=useState(0); const [noteNames,setNoteNames]=useState(false); const [accidentals,setAccidentals]=useState(false); const [tonguing,setTonguing]=useState(false); const [fingering,setFingering]=useState(false); const [rhythmMode,setRhythmMode]=useState<RhythmMode>("off"); const [zoom,setZoom]=useState(.8); const [magnify,setMagnify]=useState(1); const [fingerTip,setFingerTip]=useState<{pitch:string;x:number;y:number}|null>(null); const [theoryTip,setTheoryTip]=useState<{text:string;x:number;y:number}|null>(null); const [favorite,setFavorite]=useState(false);

  useEffect(()=>{const saved=JSON.parse(localStorage.getItem("cookie:music-favorites")||"[]") as string[];setFavorite(saved.includes(id));let mounted=true; async function load(){ try { setLoading(true); const {OpenSheetMusicDisplay}=await import("opensheetmusicdisplay"); if(!mounted||!scoreRef.current)return; scoreRef.current.replaceChildren(); const osmd=new OpenSheetMusicDisplay(scoreRef.current,{backend:"svg",autoResize:true,drawTitle:false,drawComposer:false,drawingParameters:"compacttight"}); osmd.setOptions({pageFormat:"Endless",drawMeasureNumbers:true,drawPartNames:false,drawMetronomeMarks:true}); osmd.OnXMLRead = xml=>prepareScore(xml,title); osmd.zoom=zoom; await osmd.load(asset,title); osmd.EngravingRules.MinimumDistanceBetweenSystems=12; osmd.render(); osmdRef.current=osmd; scoreRef.current.querySelectorAll<SVGGElement>(".vf-stavenote").forEach((node,index)=>{node.dataset.event=String(index);node.dataset.measure=String(measureForEvent(index,measureStarts));const pitch=scoreSequence[index];if(pitch)node.dataset.pitch=pitch});placePracticeOverlays(scoreRef.current,scoreEvents,measureStarts);addTheoryTargets(scoreRef.current);setLoading(false); } catch(e){setError(e instanceof Error?e.message:"The score could not be engraved.");setLoading(false);} } load(); return()=>{mounted=false};},[]);
  useEffect(()=>{const root=scoreRef.current;if(!root)return;root.classList.toggle("show-note-names",noteNames);root.classList.toggle("show-accidentals",accidentals);root.dataset.rhythm=rhythmMode},[noteNames,accidentals,rhythmMode,loading]);
  useEffect(()=>{ if(!osmdRef.current)return; osmdRef.current.zoom=zoom; osmdRef.current.render();window.setTimeout(()=>{if(!scoreRef.current)return;scoreRef.current.querySelectorAll<SVGGElement>(".vf-stavenote").forEach((node,index)=>{node.dataset.event=String(index);node.dataset.measure=String(measureForEvent(index,measureStarts));const pitch=scoreSequence[index];if(pitch)node.dataset.pitch=pitch});placePracticeOverlays(scoreRef.current,scoreEvents,measureStarts);addTheoryTargets(scoreRef.current)},0) },[zoom]);
  useEffect(()=>()=>{if(metroRef.current)window.clearInterval(metroRef.current);playbackTimers.current.forEach(window.clearTimeout);dronesRef.current.forEach(o=>{try{o.stop()}catch{}});audioRef.current?.close()},[]);
  const audio=()=>audioRef.current??(audioRef.current=new AudioContext());
  function scheduleClick(at:number,strong:boolean){const c=audio(),o=c.createOscillator(),g=c.createGain();o.frequency.value=strong?1250:850;g.gain.setValueAtTime(strong ? .11 : .055,at);g.gain.exponentialRampToValueAtTime(.0001,at+.06);o.connect(g).connect(c.destination);o.start(at);o.stop(at+.06);playbackNodes.current.push(o)}
  function click(){scheduleClick(audio().currentTime,accent&&metroBeat.current%4===0);metroBeat.current++}
  function toggleMetro(){if(metro){if(metroRef.current)window.clearInterval(metroRef.current);metroRef.current=null;setMetro(false)}else{metroBeat.current=0;click();metroRef.current=window.setInterval(click,60000/bpm);setMetro(true)}}
  function tapTempo(){const now=performance.now(),recent=[...metroTaps.current.filter(t=>now-t<2500),now].slice(-6);metroTaps.current=recent;if(recent.length<2)return;const intervals=recent.slice(1).map((time,index)=>time-recent[index]).filter(value=>value>=270&&value<=1500).sort((a,b)=>a-b);if(!intervals.length)return;const middle=Math.floor(intervals.length/2),interval=intervals.length%2?intervals[middle]:(intervals[middle-1]+intervals[middle])/2;setBpm(Math.max(40,Math.min(220,Math.round(60000/interval))))}
  function droneFrequency(pitch=dronePitch,octave=droneOctave){const midi=(octave+1)*12+semitones[pitch];return 440*2**((midi-69)/12)}
  function toggleDrone(pitch=dronePitch,octave=droneOctave){const key=`${pitch}${octave}`,existing=dronesRef.current.get(key);if(existing){existing.stop();dronesRef.current.delete(key)}else{const c=audio(),o=c.createOscillator(),g=c.createGain();o.type="triangle";o.frequency.value=droneFrequency(pitch,octave);g.gain.value=.027;o.connect(g).connect(c.destination);o.start();dronesRef.current.set(key,o)}setActiveDrones([...dronesRef.current.keys()]);setPicker(false)}
  function stopAllDrones(){dronesRef.current.forEach(o=>o.stop());dronesRef.current.clear();setActiveDrones([]);setPicker(false)}
  useEffect(()=>{if(picker&&activeDrones.length)stopAllDrones()},[picker]);
  function fluteTone(pitch:string,start:number,duration:number){const match=pitch.match(/^([A-G][♯♭]?)(\d)$/);if(!match)return;const c=audio(),fund=c.createOscillator(),gain=c.createGain(),vibrato=c.createOscillator(),vibGain=c.createGain(),frequency=droneFrequency(match[1],+match[2]);fund.type="sine";fund.frequency.value=frequency;vibrato.frequency.value=5.2;vibGain.gain.value=frequency*.004;vibrato.connect(vibGain);vibGain.connect(fund.frequency);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(.075,start+.035);gain.gain.setValueAtTime(.07,start+Math.max(.05,duration-.07));gain.gain.exponentialRampToValueAtTime(.0001,start+duration);fund.connect(gain).connect(c.destination);fund.start(start);vibrato.start(start);fund.stop(start+duration);vibrato.stop(start+duration);playbackNodes.current.push(fund,vibrato)}
  function stopPlayback(){playbackTimers.current.forEach(window.clearTimeout);playbackTimers.current=[];playbackNodes.current.forEach(o=>{try{o.stop()}catch{}});playbackNodes.current=[];scoreRef.current?.querySelectorAll(".playback-active").forEach(n=>n.classList.remove("playback-active"));setPlaying(false)}
  function togglePlayback(){if(playing){stopPlayback();return}if(metroRef.current)window.clearInterval(metroRef.current);setPlaying(true);let cursor=0;const c=audio(),audioStart=c.currentTime+.08,unit=60000/bpm/4,nodes=scoreRef.current?.querySelectorAll<SVGGElement>(".vf-stavenote")||[],first=measureStarts[startMeasure-1]||0;scoreEvents.slice(first).forEach((event,offset)=>{const index=first+offset,start=cursor;playbackTimers.current.push(window.setTimeout(()=>{nodes.forEach(n=>n.classList.remove("playback-active"));nodes[index]?.classList.add("playback-active")},start+80));if(event.p)fluteTone(event.p,audioStart+start/1000,Math.max(.09,event.d*unit/1000*.88));cursor+=event.d*unit});if(metro){const beatMs=60000/bpm;for(let time=0,beat=0;time<cursor;time+=beatMs,beat++)scheduleClick(audioStart+time/1000,accent&&beat%4===0)}playbackTimers.current.push(window.setTimeout(stopPlayback,cursor+160))}
  function point(e:PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*e.currentTarget.width/r.width,y:(e.clientY-r.top)*e.currentTarget.height/r.height}}
  function begin(e:PointerEvent<HTMLCanvasElement>){if(!annotating)return;drawing.current=true;const p=point(e),c=e.currentTarget.getContext("2d");c?.beginPath();c?.moveTo(p.x,p.y);e.currentTarget.setPointerCapture(e.pointerId)}
  function draw(e:PointerEvent<HTMLCanvasElement>){if(!drawing.current||!annotating)return;const p=point(e),c=e.currentTarget.getContext("2d");if(!c)return;c.lineWidth=eraser?28:4;c.lineCap="round";c.globalCompositeOperation=eraser?"destination-out":"source-over";c.strokeStyle=inkColor;c.lineTo(p.x,p.y);c.stroke()}
  function pushHistory(data:string){inkHistory.current=inkHistory.current.slice(0,inkIndex.current+1);inkHistory.current.push(data);inkIndex.current=inkHistory.current.length-1;localStorage.setItem(`cookie:${id}:ink`,data);setHistoryTick(v=>v+1)}
  function saveInk(){drawing.current=false;const data=canvasRef.current?.toDataURL();if(data)pushHistory(data)}
  function showHistory(index:number){const canvas=canvasRef.current;if(!canvas)return;const context=canvas.getContext("2d");context?.clearRect(0,0,1600,2200);const data=inkHistory.current[index];if(data){const image=new Image();image.onload=()=>context?.drawImage(image,0,0);image.src=data}inkIndex.current=index;if(data)localStorage.setItem(`cookie:${id}:ink`,data);else localStorage.removeItem(`cookie:${id}:ink`);setHistoryTick(v=>v+1)}
  function undoInk(){if(inkIndex.current>0)showHistory(inkIndex.current-1)} function redoInk(){if(inkIndex.current<inkHistory.current.length-1)showHistory(inkIndex.current+1)}
  function clearInk(){const canvas=canvasRef.current;canvas?.getContext("2d")?.clearRect(0,0,1600,2200);if(canvas)pushHistory(canvas.toDataURL())}
  useEffect(()=>{const saved=localStorage.getItem(`cookie:${id}:ink`),canvas=canvasRef.current;if(!canvas)return;const blank=canvas.toDataURL();inkHistory.current=[blank];inkIndex.current=0;if(saved){const image=new Image();image.onload=()=>{canvas.getContext("2d")?.drawImage(image,0,0);inkHistory.current.push(saved);inkIndex.current=1;setHistoryTick(v=>v+1)};image.src=saved}},[]);
  function scoreMove(e:React.MouseEvent<HTMLDivElement>){const theory=(e.target as Element).closest<SVGElement>("[data-theory]");setTheoryTip(theory?{text:theory.dataset.theory!,x:e.clientX,y:e.clientY}:null);const node=(e.target as Element).closest<SVGGElement>(".vf-stavenote[data-pitch]");if(!node){setFingerTip(null);return}const pitch=node.dataset.pitch!;if(fingering)setFingerTip({pitch,x:e.clientX,y:e.clientY})}
  function scoreClick(e:React.MouseEvent<HTMLDivElement>){const node=(e.target as Element).closest<SVGGElement>(".vf-stavenote[data-pitch]");if(!node||annotating)return;const match=node.dataset.pitch!.match(/^([A-G][♯♭]?)(\d)$/);if(!match)return;setStartMeasure(Number(node.dataset.measure)||1);setDronePitch(match[1]);setDroneOctave(+match[2]);toggleDrone(match[1],+match[2])}
  function toggleFavorite(){const saved=JSON.parse(localStorage.getItem("cookie:music-favorites")||"[]") as string[],next=saved.includes(id)?saved.filter(item=>item!==id):[...saved,id];localStorage.setItem("cookie:music-favorites",JSON.stringify(next));setFavorite(next.includes(id));window.dispatchEvent(new Event("cookie:favorites-updated"))}
  return <main className="app-shell" style={{"--viewer-magnify":magnify} as React.CSSProperties}>
    <section className="workspace"><header className="topbar"><div><a className="back" href={backHref} aria-label="Back">‹</a><span className="file-kind">SCORE</span><strong>{title}</strong><span className="saved">● MusicXML</span></div><div><button className={favorite?"icon-btn favorite active":"icon-btn favorite"} onClick={toggleFavorite}>{favorite?"♥ Saved":"♡ Save"}</button><button className="icon-btn">↗ Share</button><button className="icon-btn">•••</button></div></header>
      <div className="practice-bar"><div className="tool-group"><button data-tip="Show pitch letters beneath notes" className={noteNames?"tool on has-tip":"tool has-tip"} onClick={()=>setNoteNames(!noteNames)}><span>A♭</span>Note names</button><button data-tip="Show a colored ♯ above implied F-sharps" className={accidentals?"tool on has-tip":"tool has-tip"} onClick={()=>setAccidentals(!accidentals)}><span>♯</span>Accidentals</button><button data-tip="Tonguing overlay is paused for now" className="tool disabled has-tip" disabled><span>•</span>Tonguing</button><div className="rhythm-hover"><button className={rhythmMode!=="off"?"tool on":"tool"} onClick={()=>setRhythmMode(rhythmMode==="off"?"counts":"off")}><span>▥</span>Rhythm</button><div className="rhythm-pop"><strong>Rhythm display</strong><button className={rhythmMode==="off"?"selected":""} onClick={()=>setRhythmMode("off")}>Off</button><button className={rhythmMode==="counts"?"selected":""} onClick={()=>setRhythmMode("counts")}>1 e + a counts</button><button className={rhythmMode==="bars"?"selected":""} onClick={()=>setRhythmMode("bars")}>Beat sticks</button></div></div><button data-tip="Activate, then hover over a note" className={fingering?"tool on has-tip":"tool has-tip"} onClick={()=>setFingering(!fingering)}><span>●○</span>Fingering</button><button data-tip="Draw teaching notes on the page" className={annotating?"tool on coral has-tip":"tool has-tip"} onClick={()=>setAnnotating(!annotating)}><span>✎</span>Mark up</button></div>
        <div className="transport"><button data-tip={`Starts from the last clicked note's measure: ${startMeasure}`} className={playing?"score-play active has-tip":"score-play has-tip"} onClick={togglePlayback}>{playing?"■ Stop":"▶ Play"}</button><div className="tempo"><input aria-label="Tempo" type="range" min="40" max="220" value={bpm} onChange={e=>setBpm(+e.target.value)}/><span><b>{bpm}</b> BPM</span></div><div className="metro-hover"><button data-tip="Steady click at the selected tempo" className={metro?"audio-tool active has-tip":"audio-tool has-tip"} onClick={toggleMetro}><span>♩</span>Metronome</button><div className="metro-pop"><strong>Metronome</strong><button className="viewer-tap-tempo" onClick={tapTempo}>Tap tempo</button><label className="accent-switch"><input type="checkbox" checked={accent} onChange={e=>setAccent(e.target.checked)}/><span/>Accent beat 1</label></div></div><div className="drone-wrap"><button data-tip="Click score notes to toggle independent drones" className={activeDrones.length?"audio-tool active has-tip":"audio-tool has-tip"} onClick={()=>setPicker(!picker)}><span>◉</span>Drone <b>{activeDrones.length?activeDrones.join("+"):"off"}</b></button>{picker&&<div className="drone-pop chromatic"><strong>Choose a drone pitch</strong><div className="pitch-grid">{pitchClasses.map(n=><button className={n===dronePitch?"selected":""} key={n} onClick={()=>setDronePitch(n)}>{n}</button>)}</div><label>Octave <select value={droneOctave} onChange={e=>setDroneOctave(+e.target.value)}>{[3,4,5,6].map(o=><option key={o}>{o}</option>)}</select></label><button className="start-drone" onClick={()=>toggleDrone(dronePitch,droneOctave)}>{activeDrones.includes(`${dronePitch}${droneOctave}`)?"Stop":"Start"} {dronePitch}{droneOctave}</button>{activeDrones.length>0&&<div className="active-drone-list">{activeDrones.map(n=><button key={n} onClick={()=>toggleDrone(n.slice(0,-1),+n.slice(-1))}>{n} ×</button>)}<button onClick={stopAllDrones}>Stop all</button></div>}<small>Click any score note to add or remove that drone.</small></div>}</div></div></div>
      {annotating&&<div className="markup-row"><button onClick={undoInk} disabled={inkIndex.current<=0}>↶ Undo</button><button onClick={redoInk} disabled={inkIndex.current>=inkHistory.current.length-1}>↷ Redo</button><span className="divider"/>{["#e45d46","#2e6fb0","#3b7a57","#242623"].map(c=><button aria-label={`Use ${c}`} key={c} className={inkColor===c&&!eraser?"swatch chosen":"swatch"} style={{background:c}} onClick={()=>{setInkColor(c);setEraser(false)}}/>)}<button className={eraser?"eraser chosen":"eraser"} onClick={()=>setEraser(true)}>⌫ Eraser</button><button className="clear" onClick={clearInk}>Clear page</button><small>Markup is saved automatically.</small><i>{historyTick>=0?"":""}</i></div>}
      <div className="score-scroll"><div className="score-paper engraved"><div className="custom-score-heading"><p>FLUTE</p><h1>{title}</h1><span>{config.subtitle??"Flute"}</span></div>{loading&&<div className="score-loading">Engraving the MusicXML score…</div>}{error&&<div className="score-error">{error}</div>}<div ref={scoreRef} className="osmd-score" onMouseMove={scoreMove} onMouseLeave={()=>{setFingerTip(null);setTheoryTip(null)}} onClick={scoreClick}/><canvas ref={canvasRef} width="1600" height="2200" className={annotating?"ink active":"ink"} onPointerDown={begin} onPointerMove={draw} onPointerUp={saveInk} onPointerCancel={saveInk}/></div></div>
      <footer className="statusbar"><span>MusicXML engraving · Flute</span><span className="viewer-zoom-group"><b>Reflow</b><button onClick={()=>setZoom(Math.max(.55,zoom-.1))}>−</button>{Math.round(zoom*100)}%<button onClick={()=>setZoom(Math.min(1.25,zoom+.1))}>＋</button><b>Magnify</b><button onClick={()=>setMagnify(Math.max(.75,magnify-.1))}>−</button>{Math.round(magnify*100)}%<button onClick={()=>setMagnify(Math.min(1.5,magnify+.1))}>＋</button></span></footer>
    </section>{theoryTip&&<div className="theory-tip" style={{left:theoryTip.x+14,top:theoryTip.y+14}}><small>MUSIC THEORY</small><p>{theoryTip.text}</p></div>}{fingerTip&&<div className="flute-tip wfg full" style={{left:fingerTip.x+14,top:fingerTip.y-145}}><strong>{fingerTip.pitch}</strong><div className="full-flute-chart"><span className="thumb-keys"><i className={fingeringOn(fingerTip.pitch,"TBb")?"flute-key thumb-bb pressed":"flute-key thumb-bb"}/><i className={fingeringOn(fingerTip.pitch,"T")?"flute-key thumb-main pressed":"flute-key thumb-main"}/></span><i className={fingeringOn(fingerTip.pitch,"LP")?"flute-key left-pinky pressed":"flute-key left-pinky"}/><span className="main-keys">{[1,2,3].map(n=><i key={`l${n}`} className={fingeringOn(fingerTip.pitch,`L${n}`)?"flute-key round pressed":"flute-key round"}/>)}<i/>{[1,2,3].map(n=><i key={`r${n}`} className={fingeringOn(fingerTip.pitch,`R${n}`)?"flute-key round pressed":"flute-key round"}/>)}</span><span className="trill-keys"><i className={fingeringOn(fingerTip.pitch,"TR1")?"flute-key trill pressed":"flute-key trill"}/><i className={fingeringOn(fingerTip.pitch,"TR2")?"flute-key trill pressed":"flute-key trill"}/></span><span className="right-pinky-cluster"><i className={fingeringOn(fingerTip.pitch,"RB")?"flute-key b-key pressed":"flute-key b-key"}/><i className={fingeringOn(fingerTip.pitch,"RC")?"flute-key c-key pressed":"flute-key c-key"}/><i className={fingeringOn(fingerTip.pitch,"RCs")?"flute-key cs-key pressed":"flute-key cs-key"}/><i className={fingeringOn(fingerTip.pitch,"REb")?"flute-key eb-key pressed":"flute-key eb-key"}/></span></div><small>thumb · left pinky · left hand | right hand · trill keys · B / C / C♯ / E♭</small></div>}</main>
}

export default function MysteryOfLovePage(){return <ScoreViewer/>}
