"use client";

import { PointerEvent, useEffect, useRef, useState } from "react";

type Note = { pitch: string; duration: number; rest?: boolean };
const phrase: Note[][] = [
  [{ pitch: "B4", duration: 6 }, { pitch: "G4", duration: 2 }, { pitch: "B4", duration: 2 }, { pitch: "A4", duration: 1 }, { pitch: "G4", duration: 1 }, { pitch: "G4", duration: 2 }, { pitch: "E4", duration: 2 }],
  [{ pitch: "D4", duration: 12 }, { pitch: "rest", duration: 4, rest: true }],
  [{ pitch: "E4", duration: 4 }, { pitch: "F♯4", duration: 4 }, { pitch: "G4", duration: 4 }, { pitch: "D5", duration: 4 }],
  [{ pitch: "B4", duration: 8 }, { pitch: "A4", duration: 8 }],
];
const measures = Array.from({ length: 16 }, (_, i) => phrase[i % 4]);
const pitchIndex: Record<string, number> = { D4: 0, E4: 1, "F♯4": 2, G4: 3, A4: 4, B4: 5, D5: 7 };
const fingerings: Record<string, string> = { D4: "● ● ●  |  ● ● ●", E4: "● ● ●  |  ● ● ○", "F♯4": "● ● ●  |  ● ○ ○", G4: "● ● ●  |  ○ ○ ○", A4: "● ● ○  |  ○ ○ ○", B4: "● ○ ○  |  ○ ○ ○", D5: "○ ● ●  |  ● ● ○" };
const frequencies: Record<string, number> = { D4: 293.66, E4: 329.63, "F♯4": 369.99, G4: 392, A4: 440, B4: 493.88, D5: 587.33 };
const droneNotes = ["C4", "D4", "E4", "F4", "G4", "A4", "B4"];
const droneFreq: Record<string, number> = { C4: 261.63, D4: 293.66, E4: 329.63, F4: 349.23, G4: 392, A4: 440, B4: 493.88 };

export default function Home() {
  const [noteNames, setNoteNames] = useState(false); const [tonguing, setTonguing] = useState(false); const [rhythm, setRhythm] = useState(false); const [annotating, setAnnotating] = useState(false);
  const [playing, setPlaying] = useState(false); const [metro, setMetro] = useState(false); const [drone, setDrone] = useState(false); const [dronePicker, setDronePicker] = useState(false);
  const [droneNote, setDroneNote] = useState("G4"); const [bpm, setBpm] = useState(76); const [activeMeasure, setActiveMeasure] = useState(-1); const [activeNote, setActiveNote] = useState("");
  const [tip, setTip] = useState<{ pitch: string; x: number; y: number } | null>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null); const drawing = useRef(false); const audioRef = useRef<AudioContext | null>(null); const droneRef = useRef<OscillatorNode | null>(null);
  const playbackTimers = useRef<number[]>([]); const metroTimer = useRef<number | null>(null);
  const audio = () => audioRef.current ?? (audioRef.current = new AudioContext());
  const tone = (frequency: number, length = .13, volume = .07) => { const context = audio(); const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.type = "sine"; oscillator.frequency.value = frequency; gain.gain.setValueAtTime(volume, context.currentTime); gain.gain.exponentialRampToValueAtTime(.0001, context.currentTime + length); oscillator.connect(gain).connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + length); };
  function stopPlayback() { playbackTimers.current.forEach(window.clearTimeout); playbackTimers.current = []; setPlaying(false); setActiveMeasure(-1); setActiveNote(""); }
  function playScore() { if (playing) return stopPlayback(); setPlaying(true); let cursor = 0; const unit = 60000 / bpm / 4; measures.forEach((measure, mi) => measure.forEach((note) => { const marker = cursor; playbackTimers.current.push(window.setTimeout(() => { setActiveMeasure(mi); setActiveNote(`${mi}-${note.pitch}-${marker}`); if (!note.rest) tone(frequencies[note.pitch], Math.max(.1, note.duration * unit / 1000 * .78), .055); }, cursor)); cursor += note.duration * unit; })); playbackTimers.current.push(window.setTimeout(stopPlayback, cursor + 100)); }
  function toggleMetro() { if (metro) { if (metroTimer.current) window.clearInterval(metroTimer.current); metroTimer.current = null; setMetro(false); return; } setMetro(true); tone(880, .06, .08); metroTimer.current = window.setInterval(() => tone(880, .06, .08), 60000 / bpm); }
  function toggleDrone(note = droneNote) { if (droneRef.current) { droneRef.current.stop(); droneRef.current = null; setDrone(false); return; } const context = audio(); const osc = context.createOscillator(); const gain = context.createGain(); osc.type = "triangle"; osc.frequency.value = droneFreq[note]; gain.gain.value = .035; osc.connect(gain).connect(context.destination); osc.start(); droneRef.current = osc; setDrone(true); setDronePicker(false); }
  useEffect(() => () => { playbackTimers.current.forEach(window.clearTimeout); if (metroTimer.current) window.clearInterval(metroTimer.current); try { droneRef.current?.stop(); } catch {} audioRef.current?.close(); }, []);
  function point(event: PointerEvent<HTMLCanvasElement>) { const rect = event.currentTarget.getBoundingClientRect(); return { x: (event.clientX - rect.left) * event.currentTarget.width / rect.width, y: (event.clientY - rect.top) * event.currentTarget.height / rect.height }; }
  function beginDraw(event: PointerEvent<HTMLCanvasElement>) { if (!annotating) return; drawing.current = true; const p = point(event); const ctx = event.currentTarget.getContext("2d"); ctx?.beginPath(); ctx?.moveTo(p.x, p.y); event.currentTarget.setPointerCapture(event.pointerId); }
  function draw(event: PointerEvent<HTMLCanvasElement>) { if (!drawing.current || !annotating) return; const p = point(event); const ctx = event.currentTarget.getContext("2d"); if (!ctx) return; ctx.lineWidth = 4; ctx.lineCap = "round"; ctx.strokeStyle = "#e45d46"; ctx.lineTo(p.x, p.y); ctx.stroke(); }
  function clearInk() { canvasRef.current?.getContext("2d")?.clearRect(0, 0, 1400, 900); }

  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><span>◒</span><strong>Long Tone</strong><small>FLUTE STUDIO</small></div><label className="search"><span>⌕</span><input aria-label="Search music" placeholder="Search your library" /></label><div className="filter-row"><button>Difficulty <b>⌄</b></button><button>Category <b>⌄</b></button></div><p className="eyebrow">YOUR MUSIC · 1</p><button className="piece active"><span className="piece-icon">♫</span><span><strong>Mystery of Love</strong><small>Flute solo · Intermediate</small><em><i>lyrical</i><i>G major</i></em></span></button><div className="empty-library"><span>＋</span><p>Add another MusicXML score</p><small>Build your teaching library</small></div><div className="profile"><span>HW</span><div><strong>Haylie&apos;s studio</strong><small>Flute · Teacher</small></div><b>•••</b></div></aside>
    <section className="workspace">
      <header className="topbar"><div><button className="back" aria-label="Back to library">‹</button><span className="file-kind">SCORE</span><strong>Mystery of Love</strong><span className="saved">● Saved</span></div><div><button className="icon-btn">↗ Share</button><button className="icon-btn">•••</button></div></header>
      <div className="practice-bar"><div className="tool-group"><button className={noteNames ? "tool on" : "tool"} onClick={() => setNoteNames(!noteNames)}><span>A♭</span>Note names</button><button className={tonguing ? "tool on" : "tool"} onClick={() => setTonguing(!tonguing)}><span>•</span>Tonguing</button><button className={rhythm ? "tool on" : "tool"} onClick={() => setRhythm(!rhythm)}><span>▥</span>Beats</button><button className={annotating ? "tool on coral" : "tool"} onClick={() => setAnnotating(!annotating)}><span>✎</span>Mark up</button>{annotating && <button className="clear" onClick={clearInk}>Clear ink</button>}</div>
        <div className="transport"><button className="round" aria-label="Previous">│‹</button><button className="play" onClick={playScore}>{playing ? "■" : "▶"}</button><div className="tempo"><input aria-label="Tempo" type="range" min="40" max="144" value={bpm} onChange={e => setBpm(+e.target.value)} /><span><b>{bpm}</b> BPM</span></div><button className={metro ? "audio-tool active" : "audio-tool"} onClick={toggleMetro}><span>♩</span>Metronome</button><div className="drone-wrap"><button className={drone ? "audio-tool active" : "audio-tool"} onClick={() => drone ? toggleDrone() : setDronePicker(!dronePicker)}><span>◉</span>Drone <b>{droneNote}</b></button>{dronePicker && <div className="drone-pop"><strong>Choose a drone pitch</strong><div>{droneNotes.map(n => <button key={n} onClick={() => { setDroneNote(n); toggleDrone(n); }}>{n.replace("4", "")}</button>)}</div><small>Tap a note to start. Tap Drone again to stop.</small></div>}</div></div>
      </div>
      <div className="score-scroll"><div className="score-paper"><div className="score-title"><p>FLUTE SOLO</p><h1>Mystery of Love</h1><span>Flute</span><em>♩ = 76 · Lyrical</em></div><div className="systems">{[0, 4, 8, 12].map(start => <div className="system" key={start}><div className="clef">𝄞</div><div className="key">♯</div><div className="time"><b>4</b><b>4</b></div>{measures.slice(start, start + 4).map((notes, offset) => { const mi = start + offset; return <div className={activeMeasure === mi ? "measure active" : "measure"} key={mi}><small className="measure-no">{mi + 1}</small>{rhythm && <div className="beat-grid">{[0,1,2,3].map(i => <i key={i} />)}</div>}<div className="staff-lines">{[0,1,2,3,4].map(i => <i key={i} />)}</div><div className="notes">{notes.map((note, ni) => { if (note.rest) return <span className="rest" key={ni}>𝄽</span>; const position = 66 - pitchIndex[note.pitch] * 6; return <button key={ni} className={`note d${note.duration} ${activeNote.startsWith(`${mi}-${note.pitch}`) ? "sounding" : ""}`} style={{ top: position, flexGrow: note.duration }} onMouseEnter={e => setTip({ pitch: note.pitch, x: e.clientX, y: e.clientY })} onMouseLeave={() => setTip(null)} onClick={() => tone(frequencies[note.pitch], .45, .06)}>{tonguing && <i className="tongue">T</i>}<b>●</b>{note.duration <= 6 && <i className="stem" />}{noteNames && <small>{note.pitch.replace("4", "").replace("5", "")}</small>}</button>; })}</div></div>; })}</div>)}</div><canvas ref={canvasRef} width="1400" height="900" className={annotating ? "ink active" : "ink"} onPointerDown={beginDraw} onPointerMove={draw} onPointerUp={() => drawing.current = false} onPointerCancel={() => drawing.current = false} /></div></div>
      <footer className="statusbar"><span>Page 1 of 1</span><span>Hover over any note for flute fingering</span><span>− &nbsp; 85% &nbsp; ＋</span></footer>
    </section>{tip && !annotating && <div className="fingering-tip" style={{ left: tip.x + 14, top: tip.y - 90 }}><span>{tip.pitch}</span><div>{fingerings[tip.pitch]}</div><small>Standard flute fingering</small></div>}
  </main>;
}
