"use client";

import { PointerEvent, useEffect, useRef, useState } from "react";
import type { OpenSheetMusicDisplay as OSMDType } from "opensheetmusicdisplay";

const pitchClasses = ["C", "C♯", "D", "E♭", "E", "F", "F♯", "G", "A♭", "A", "B♭", "B"];
const semitones: Record<string, number> = { C:0,"C♯":1,D:2,"E♭":3,E:4,F:5,"F♯":6,G:7,"A♭":8,A:9,"B♭":10,B:11 };
const scorePhrase = ["B4","G4","B4","A4","G4","G4","E4","D4",null,"E4","F♯4","G4","D5","B4","A4"];
const scoreSequence = Array.from({length:4},()=>scorePhrase).flat();
const fingeringCodes: Record<string,string> = {D4:"T 123 | 123",E4:"T 123 | 12–", "F♯4":"T 123 | ––3",G4:"T 123 | –––",A4:"T 12– | –––",B4:"T 1–– | –––",D5:"T –23 | 123"};
type RhythmMode = "off"|"counts"|"one"|"one-three"|"all";

function addLyric(document: Document, note: Element, number: string, text: string) {
  const lyric = document.createElement("lyric"); lyric.setAttribute("number", number); lyric.setAttribute("placement", "below");
  lyric.setAttribute("color", number === "90" ? "#316b53" : "#b65a3c");
  const syllabic = document.createElement("syllabic"); syllabic.textContent = "single";
  const label = document.createElement("text"); label.textContent = text; lyric.append(syllabic, label); note.appendChild(lyric);
}

function prepareScore(xml: string) {
  const document = new DOMParser().parseFromString(xml, "application/xml");
  document.querySelector("work-title")?.replaceChildren("Mystery of Love");
  document.querySelectorAll('creator[type="composer"]').forEach(node => node.remove());
  document.querySelectorAll("part > measure").forEach(measure => {
    let divisions = Number(measure.querySelector(":scope > attributes > divisions")?.textContent || 4); let offset = 0;
    measure.querySelectorAll(":scope > note").forEach(note => {
      const duration = Number(note.querySelector(":scope > duration")?.textContent || 0); const chord = !!note.querySelector(":scope > chord");
      const step = note.querySelector(":scope > pitch > step")?.textContent; const alter = Number(note.querySelector(":scope > pitch > alter")?.textContent || 0); const octave = note.querySelector(":scope > pitch > octave")?.textContent;
      if (step && octave) addLyric(document, note, "90", `${step}${alter === 1 ? "♯" : alter === -1 ? "♭" : ""}`);
      const sixteenth = Math.round(offset / divisions * 4); const beat = Math.floor(sixteenth / 4) + 1; const sub = ["", "e", "+", "a"][sixteenth % 4]; addLyric(document, note, "91", `${beat}${sub}`);
      if (!chord) offset += duration;
    });
  });
  return new XMLSerializer().serializeToString(document);
}

export default function Home() {
  const scoreRef = useRef<HTMLDivElement>(null); const canvasRef = useRef<HTMLCanvasElement>(null); const osmdRef = useRef<OSMDType | null>(null);
  const audioRef = useRef<AudioContext | null>(null); const droneRef = useRef<OscillatorNode | null>(null); const metroRef = useRef<number | null>(null); const metroBeat=useRef(0); const drawing = useRef(false);
  const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [bpm,setBpm]=useState(76); const [metro,setMetro]=useState(false); const [accent,setAccent]=useState(true); const [drone,setDrone]=useState(false); const [dronePitch,setDronePitch]=useState("G"); const [droneOctave,setDroneOctave]=useState(4); const [picker,setPicker]=useState(false); const [annotating,setAnnotating]=useState(false); const [inkColor,setInkColor]=useState("#e45d46"); const [eraser,setEraser]=useState(false); const [noteNames,setNoteNames]=useState(false); const [tonguing,setTonguing]=useState(false); const [fingering,setFingering]=useState(false); const [rhythmMode,setRhythmMode]=useState<RhythmMode>("off"); const [zoom,setZoom]=useState(.8); const [fingerTip,setFingerTip]=useState<{pitch:string;x:number;y:number}|null>(null);

  useEffect(()=>{ let mounted=true; async function load(){ try { setLoading(true); const {OpenSheetMusicDisplay}=await import("opensheetmusicdisplay"); if(!mounted||!scoreRef.current)return; scoreRef.current.replaceChildren(); const osmd=new OpenSheetMusicDisplay(scoreRef.current,{backend:"svg",autoResize:true,drawTitle:false,drawComposer:false,drawingParameters:"compacttight"}); osmd.setOptions({pageFormat:"Endless",drawMeasureNumbers:true,drawPartNames:false,drawMetronomeMarks:true}); osmd.OnXMLRead = prepareScore; osmd.zoom=zoom; await osmd.load("/mystery-of-love.mxl","Mystery of Love"); osmd.render(); osmdRef.current=osmd; const notes=scoreRef.current.querySelectorAll<SVGGElement>(".vf-stavenote"); notes.forEach((node,index)=>{const pitch=scoreSequence[index];if(pitch)node.dataset.pitch=pitch}); scoreRef.current.querySelectorAll<SVGTextElement>("text").forEach(text=>{const paint=`${text.getAttribute("fill")} ${text.getAttribute("style")}`;if(paint.includes("316b53"))text.classList.add("lyric-name");if(paint.includes("b65a3c")){text.classList.add("lyric-beat");text.dataset.beat=text.textContent?.match(/[1-4]/)?.[0]||""}}); setLoading(false); } catch(e){setError(e instanceof Error?e.message:"The score could not be engraved.");setLoading(false);} } load(); return()=>{mounted=false};},[]);
  useEffect(()=>{const root=scoreRef.current;if(!root)return;root.classList.toggle("show-note-names",noteNames);root.dataset.rhythm=rhythmMode},[noteNames,rhythmMode,loading]);
  useEffect(()=>{ if(!osmdRef.current)return; osmdRef.current.zoom=zoom; osmdRef.current.render(); },[zoom]);
  useEffect(()=>()=>{if(metroRef.current)window.clearInterval(metroRef.current);try{droneRef.current?.stop()}catch{}audioRef.current?.close()},[]);
  const audio=()=>audioRef.current??(audioRef.current=new AudioContext());
  function click(){const c=audio(),o=c.createOscillator(),g=c.createGain(),strong=accent&&metroBeat.current%4===0;o.frequency.value=strong?1250:850;g.gain.setValueAtTime(strong ? .11 : .055,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.06);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.06);metroBeat.current++}
  function toggleMetro(){if(metro){if(metroRef.current)window.clearInterval(metroRef.current);metroRef.current=null;setMetro(false)}else{metroBeat.current=0;click();metroRef.current=window.setInterval(click,60000/bpm);setMetro(true)}}
  function droneFrequency(pitch=dronePitch,octave=droneOctave){const midi=(octave+1)*12+semitones[pitch];return 440*2**((midi-69)/12)}
  function toggleDrone(pitch=dronePitch,octave=droneOctave){if(droneRef.current){droneRef.current.stop();droneRef.current=null;setDrone(false);return}const c=audio(),o=c.createOscillator(),g=c.createGain();o.type="triangle";o.frequency.value=droneFrequency(pitch,octave);g.gain.value=.035;o.connect(g).connect(c.destination);o.start();droneRef.current=o;setDrone(true);setPicker(false)}
  function point(e:PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*e.currentTarget.width/r.width,y:(e.clientY-r.top)*e.currentTarget.height/r.height}}
  function begin(e:PointerEvent<HTMLCanvasElement>){if(!annotating)return;drawing.current=true;const p=point(e),c=e.currentTarget.getContext("2d");c?.beginPath();c?.moveTo(p.x,p.y);e.currentTarget.setPointerCapture(e.pointerId)}
  function draw(e:PointerEvent<HTMLCanvasElement>){if(!drawing.current||!annotating)return;const p=point(e),c=e.currentTarget.getContext("2d");if(!c)return;c.lineWidth=eraser?28:4;c.lineCap="round";c.globalCompositeOperation=eraser?"destination-out":"source-over";c.strokeStyle=inkColor;c.lineTo(p.x,p.y);c.stroke()}
  function saveInk(){drawing.current=false;const data=canvasRef.current?.toDataURL();if(data)localStorage.setItem("long-tone:mystery-of-love:ink",data)}
  function clearInk(){canvasRef.current?.getContext("2d")?.clearRect(0,0,1600,2200);localStorage.removeItem("long-tone:mystery-of-love:ink")}
  useEffect(()=>{const saved=localStorage.getItem("long-tone:mystery-of-love:ink"),canvas=canvasRef.current;if(!saved||!canvas)return;const image=new Image();image.onload=()=>canvas.getContext("2d")?.drawImage(image,0,0);image.src=saved},[]);
  function scoreMove(e:React.MouseEvent<HTMLDivElement>){const node=(e.target as Element).closest<SVGGElement>(".vf-stavenote[data-pitch]");if(!node){setFingerTip(null);return}const pitch=node.dataset.pitch!;if(fingering)setFingerTip({pitch,x:e.clientX,y:e.clientY})}
  function scoreClick(e:React.MouseEvent<HTMLDivElement>){const node=(e.target as Element).closest<SVGGElement>(".vf-stavenote[data-pitch]");if(!node||annotating)return;const match=node.dataset.pitch!.match(/^([A-G][♯♭]?)(\d)$/);if(!match)return;if(droneRef.current){droneRef.current.stop();droneRef.current=null}setDronePitch(match[1]);setDroneOctave(+match[2]);setDrone(false);setTimeout(()=>toggleDrone(match[1],+match[2]))}
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span>◒</span><strong>Long Tone</strong><small>FLUTE STUDIO</small></div><label className="search"><span>⌕</span><input aria-label="Search music" placeholder="Search your library" /></label><div className="filter-row"><button>Difficulty <b>⌄</b></button><button>Category <b>⌄</b></button></div><p className="eyebrow">YOUR MUSIC · 1</p><button className="piece active"><span className="piece-icon">♫</span><span><strong>Mystery of Love</strong><small>Flute solo · Intermediate</small><em><i>lyrical</i><i>G major</i></em></span></button><div className="profile"><span>HW</span><div><strong>Haylie&apos;s studio</strong><small>Flute · Teacher</small></div><b>•••</b></div></aside>
    <section className="workspace"><header className="topbar"><div><button className="back">‹</button><span className="file-kind">SCORE</span><strong>Mystery of Love</strong><span className="saved">● MusicXML</span></div><div><button className="icon-btn">↗ Share</button><button className="icon-btn">•••</button></div></header>
      <div className="practice-bar"><div className="tool-group"><button data-tip="Show pitch letters beneath notes" className={noteNames?"tool on has-tip":"tool has-tip"} onClick={()=>setNoteNames(!noteNames)}><span>A♭</span>Note names</button><button data-tip="Tonguing overlay comes next" className={tonguing?"tool pending has-tip":"tool has-tip"} onClick={()=>setTonguing(!tonguing)}><span>•</span>Tonguing</button><label className="rhythm-select has-tip" data-tip="Choose how beats are marked"><span>▥</span><select value={rhythmMode} onChange={e=>setRhythmMode(e.target.value as RhythmMode)}><option value="off">Rhythm off</option><option value="counts">1 e + a</option><option value="one">Beat 1</option><option value="one-three">Beats 1 & 3</option><option value="all">Beats 1–4</option></select></label><button data-tip="Activate, then hover over a note" className={fingering?"tool on has-tip":"tool has-tip"} onClick={()=>setFingering(!fingering)}><span>●○</span>Fingering</button><button data-tip="Draw teaching notes on the page" className={annotating?"tool on coral has-tip":"tool has-tip"} onClick={()=>setAnnotating(!annotating)}><span>✎</span>Mark up</button>{annotating&&<div className="ink-tools">{["#e45d46","#2e6fb0","#3b7a57","#242623"].map(c=><button aria-label={`Use ${c}`} key={c} className={inkColor===c&&!eraser?"swatch chosen":"swatch"} style={{background:c}} onClick={()=>{setInkColor(c);setEraser(false)}}/>)}<button className={eraser?"eraser chosen":"eraser"} onClick={()=>setEraser(true)}>Eraser</button><button className="clear" onClick={clearInk}>Clear</button></div>}</div>
        <div className="transport"><div className="tempo"><input aria-label="Tempo" type="range" min="40" max="144" value={bpm} onChange={e=>setBpm(+e.target.value)}/><span><b>{bpm}</b> BPM</span></div><button data-tip="Steady click at the selected tempo" className={metro?"audio-tool active has-tip":"audio-tool has-tip"} onClick={toggleMetro}><span>♩</span>Metronome</button><button data-tip="Make beat 1 louder in 4/4" className={accent?"accent-button active has-tip":"accent-button has-tip"} onClick={()=>setAccent(!accent)}>1› 2 3 4</button><div className="drone-wrap"><button data-tip="Choose a pitch, or click a score note" className={drone?"audio-tool active has-tip":"audio-tool has-tip"} onClick={()=>drone?toggleDrone():setPicker(!picker)}><span>◉</span>Drone <b>{dronePitch}{droneOctave}</b></button>{picker&&<div className="drone-pop chromatic"><strong>Choose a drone pitch</strong><div className="pitch-grid">{pitchClasses.map(n=><button className={n===dronePitch?"selected":""} key={n} onClick={()=>setDronePitch(n)}>{n}</button>)}</div><label>Octave <select value={droneOctave} onChange={e=>setDroneOctave(+e.target.value)}>{[3,4,5,6].map(o=><option key={o}>{o}</option>)}</select></label><button className="start-drone" onClick={()=>toggleDrone(dronePitch,droneOctave)}>Start {dronePitch}{droneOctave}</button><small>Or close this and click any note in the score.</small></div>}</div></div></div>
      <div className="score-scroll"><div className="score-paper engraved"><div className="custom-score-heading"><p>FLUTE SOLO</p><h1>Mystery of Love</h1><span>Flute</span></div>{loading&&<div className="score-loading">Engraving the MusicXML score…</div>}{error&&<div className="score-error">{error}</div>}<div ref={scoreRef} className="osmd-score" onMouseMove={scoreMove} onMouseLeave={()=>setFingerTip(null)} onClick={scoreClick}/><canvas ref={canvasRef} width="1600" height="2200" className={annotating?"ink active":"ink"} onPointerDown={begin} onPointerMove={draw} onPointerUp={saveInk} onPointerCancel={saveInk}/></div></div>
      <footer className="statusbar"><span>MusicXML engraving · Flute</span><span>Notation rendered from the attached score</span><span><button onClick={()=>setZoom(Math.max(.55,zoom-.1))}>−</button> {Math.round(zoom*100)}% <button onClick={()=>setZoom(Math.min(1.25,zoom+.1))}>＋</button></span></footer>
    </section>{fingerTip&&<div className="flute-tip" style={{left:fingerTip.x+14,top:fingerTip.y-105}}><strong>{fingerTip.pitch}</strong><div className="flute-diagram">{[0,1,2,3,4,5].map((k)=><i key={k} className={fingeringCodes[fingerTip.pitch]?.replace(/[^123]/g,"").length>k?"closed":""}/>)}</div><code>{fingeringCodes[fingerTip.pitch]}</code><small>Standard flute fingering</small></div>}</main>
}
