"use client";

import {useEffect,useRef,useState} from "react";
import type {OpenSheetMusicDisplay as OSMDType} from "opensheetmusicdisplay";
import "./scales.css";

const tonics=["C","G","D","A","E","F","B♭","E♭","A♭"] as const;
const tonicPc:Record<string,number>={C:0,G:7,D:2,A:9,E:4,F:5,"B♭":10,"E♭":3,"A♭":8};
const types={major:[0,2,4,5,7,9,11],"natural minor":[0,2,3,5,7,8,10],"harmonic minor":[0,2,3,5,7,8,11],"melodic minor":[0,2,3,5,7,9,11]} as const;
type ScaleType=keyof typeof types;type Range="one octave"|"two octaves"|"C4–C7"|"B3–D7";type Articulation="all tongued"|"all slurred"|"slur two"|"two tongued, two slurred";

function scaleMidis(tonic:string,type:ScaleType,range:Range){const pc=tonicPc[tonic],min=range==="B3–D7"?59:60,max=range==="B3–D7"?98:96;let start=min+((pc-min)%12+12)%12,end=range==="one octave"?start+12:range==="two octaves"?start+24:max-((max-pc)%12+12)%12;const up:number[]=[];for(let octave=start;octave<=end;octave+=12)for(const interval of types[type])if(octave+interval<=end)up.push(octave+interval);if(up.at(-1)!==end)up.push(end);const down=[...up].slice(0,-1).reverse();if(type==="melodic minor")return [...up,...down.map(m=>{const degree=(m-pc+120)%12;return degree===9||degree===11?m-1:m})];return [...up,...down]}
function xmlPitch(midi:number){const names=[{s:"C",a:0},{s:"C",a:1},{s:"D",a:0},{s:"D",a:1},{s:"E",a:0},{s:"F",a:0},{s:"F",a:1},{s:"G",a:0},{s:"G",a:1},{s:"A",a:0},{s:"A",a:1},{s:"B",a:0}],p=names[midi%12];return `<pitch><step>${p.s}</step>${p.a?`<alter>${p.a}</alter>`:""}<octave>${Math.floor(midi/12)-1}</octave></pitch>`}
function scoreXml(tonic:string,type:ScaleType,range:Range,articulation:Articulation){const notes=scaleMidis(tonic,type,range),measures:Array<string>=[];for(let m=0;m<Math.ceil(notes.length/8);m++){const chunk=notes.slice(m*8,m*8+8),body=chunk.map((midi,i)=>{const index=m*8+i,last=index===notes.length-1,pairStart=index%2===0;let notation="";if(articulation==="all slurred"&&(index===0||last))notation=`<notations><slur type="${index===0?"start":"stop"}" number="1"/></notations>`;if(articulation==="slur two")notation=`<notations><slur type="${pairStart?"start":"stop"}" number="1"/></notations>`;if(articulation==="two tongued, two slurred"&&index%4>=2)notation=`<notations><slur type="${index%4===2?"start":"stop"}" number="1"/></notations>`;return `<note>${xmlPitch(midi)}<duration>1</duration><voice>1</voice><type>eighth</type>${notation}</note>`}).join("");measures.push(`<measure number="${m+1}">${m===0?`<attributes><divisions>1</divisions><key><fifths>0</fifths></key><time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes><direction placement="above"><direction-type><words>${tonic} ${type} · ${range} · ${articulation}</words></direction-type></direction>`:""}${body}</measure>`)}return `<?xml version="1.0" encoding="UTF-8"?><score-partwise version="3.1"><work><work-title>${tonic} ${type} scale</work-title></work><part-list><score-part id="P1"><part-name>Flute</part-name></score-part></part-list><part id="P1">${measures.join("")}</part></score-partwise>`}

export default function ScaleStudio(){const root=useRef<HTMLDivElement>(null),osmd=useRef<OSMDType|null>(null);const [tonic,setTonic]=useState("C"),[type,setType]=useState<ScaleType>("major"),[range,setRange]=useState<Range>("one octave"),[articulation,setArticulation]=useState<Articulation>("all tongued"),[ready,setReady]=useState(false);useEffect(()=>{let active=true;import("opensheetmusicdisplay").then(({OpenSheetMusicDisplay})=>{if(!active||!root.current)return;osmd.current=new OpenSheetMusicDisplay(root.current,{backend:"svg",autoResize:true,drawTitle:false,drawingParameters:"compacttight"});setReady(true)});return()=>{active=false}},[]);useEffect(()=>{if(!ready||!osmd.current)return;osmd.current.load(scoreXml(tonic,type,range,articulation)).then(()=>{if(!osmd.current)return;osmd.current.zoom=.85;osmd.current.EngravingRules.MinimumDistanceBetweenSystems=12;osmd.current.render()})},[ready,tonic,type,range,articulation]);return <main className="scale-shell"><aside className="scale-nav"><a href="/" className="studio-logo"><span>◒</span><b>Cookie</b><small>FLUTE STUDIO</small></a><nav><a href="/flute-studio"><i>⌂</i>Home</a><a href="/flute-studio/music"><i>♫</i>Music</a><a className="active" href="/flute-studio/exercises/scales"><i>◎</i>Exercises</a><a href="/flute-studio#practice"><i>✓</i>Practice</a></nav><div className="studio-profile"><span>HW</span><p><b>Haylie&apos;s studio</b><small>Flute · Teacher</small></p></div></aside><section className="scale-main"><header><div><p>EXERCISE PORTAL</p><h1>Scale Studio</h1><span>Build a scale for the range and articulation you need today.</span></div><a href="/flute-studio/music">← Music library</a></header><div className="scale-controls"><label>Key<select value={tonic} onChange={e=>setTonic(e.target.value)}>{tonics.map(t=><option key={t}>{t}</option>)}</select></label><label>Scale type<select value={type} onChange={e=>setType(e.target.value as ScaleType)}>{Object.keys(types).map(t=><option key={t}>{t}</option>)}</select></label><label>Range<select value={range} onChange={e=>setRange(e.target.value as Range)}>{["one octave","two octaves","C4–C7","B3–D7"].map(r=><option key={r}>{r}</option>)}</select></label><label>Articulation<select value={articulation} onChange={e=>setArticulation(e.target.value as Articulation)}>{["all tongued","all slurred","slur two","two tongued, two slurred"].map(a=><option key={a}>{a}</option>)}</select></label></div><section className="scale-paper"><div className="scale-title"><p>FLUTE SCALE</p><h2>{tonic} {type}</h2><span>{range} · {articulation}</span></div><div ref={root} className="scale-score"/></section></section></main>}
